login-type = vpn_Username_Password
password-factor = password
tunnel-type = ssl
ignore-server-cert = true
no-routing = true
add-routes = 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
ip-lease-time = 28800

